### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by walles** [walles/batterylogger#2]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gmail.walles.johan.batterylogger/com.gmail.walles.johan.batterylogger.MainActivity}: java.lang.IllegalArgumentException: Must get at least one number to compute average
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
at android.app.ActivityThread.access$600(ActivityThread.java:140)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4898)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Must get at least one number to compute average
at com.gmail.walles.johan.batterylogger.DrainLinesCreator.average(DrainLinesCreator.java:76)
at com.gmail.walles.johan.batterylogger.DrainLinesCreator.getDrainLineLevel(DrainLinesCreator.java:123)
at com.gmail.walles.johan.batterylogger.DrainLinesCreator.createDrainLine(DrainLinesCreator.java:162)
at com.gmail.walles.johan.batterylogger.DrainLinesCreator.finishLine(DrainLinesCreator.java:171)
at com.gmail.walles.johan.batterylogger.DrainLinesCreator.handleEvent(DrainLinesCreator.java:187)
at com.gmail.walles.johan.batterylogger.DrainLinesCreator.getDrainLines(DrainLinesCreator.java:226)
at com.gmail.walles.johan.batterylogger.History.getDrainLines(History.java:203)
at com.gmail.walles.johan.batterylogger.BatteryPlotFragment.addPlotData(BatteryPlotFragment.java:444)
at com.gmail.walles.johan.batterylogger.BatteryPlotFragment.onCreateView(BatteryPlotFragment.java:275)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1504)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1121)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1484)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:571)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1167)
at android.app.Activity.performStart(Activity.java:5216)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2073)
... 11 more```

**Comment by walles** [comment]
Lots of fixes have gone in since this happened and I haven't seen it in a long time, closing.
